### ISSUE TITLE
Install a soundfont for SLADE

### ISSUE THREAD

**Issue by Calinou** [flathub/net.mancubus.SLADE#12]
When running SLADE 3.1.8 using the Flatpak, I get the following error messages in standard output:

```text
❯ flatpak run net.mancubus.SLADE
fluidsynth: error: Unable to open file "/usr/share/sounds/sf2/FluidR3_GS.sf2"
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf2/FluidR3_GS.sf2"
fluidsynth: error: Unable to open file "/usr/share/sounds/sf2/FluidR3_GM.sf2"
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf2/FluidR3_GM.sf2"
fluidsynth: warning: Failed to set thread to high priority
```

It'd be good to install a soundfont so that MIDIs can be listened to directly in SLADE.

**Comment by Eonfge** [comment]
We already have Fluidsynth in the package, so we could just use the GZDoom SoundFont. Does that sound reasonable?

Also, I assume you were talking about SLADE 3.1.7 because I only just pushed the 3.1.8 update :p

**Comment by Calinou** [comment]
> We already have Fluidsynth in the package, so we could just use the GZDoom SoundFont. Does that sound reasonable?

Sounds good to me :slightly_smiling_face:

**Comment by Eonfge** [comment]
It doesn't seem to like it so much... SLADE is set to look for FluidR3_GS and FluidR3_GM. Without those, it will keep throwing the errors because the sound boards don't match.

Now, the kicker... FluidR3_GM is a 150 MB big:
https://sources.debian.org/src/fluid-soundfont/3.1-5.1/

Even then. It might take an upstream change before this works. Trying some stuff now, but it's not ideal.

Other question... we don't actually bundle the png editing tools as well. Should those also be added?

**Comment by Calinou** [comment]
@Eonfge What are the PNG editing tools in question?

**Comment by Eonfge** [comment]
- PNGout
- PNGCrush
- DeflOpt

The first one is not actually open source, so it can only be added using an "extra-data", which is annoying as hell. The others are open source, but they don't actually have that much documentation. They also don't seem to be that much of a big deal if you ask me. If you properly export images from GIMP, all of these tools are not necessary.

The thing you mention about GIMP is also a point of concern. The Editor has an 'External Editors' section which is completely unusable in Flatpak. Might be better to remove that section altogether because including GIMP is indeed overkill.

For now, I do have a version you can test with the supported audio:
https://github.com/flathub/net.mancubus.SLADE/pull/14

I also noticed another library missing... which makes me wonder if people even use SLADE... because the acc-compiler is currently not included. How do you normally use it?

**Comment by Calinou** [comment]
> I also noticed another library missing... which makes me wonder if people even use SLADE... because the acc-compiler is currently not included. How do you normally use it?

I guess people making complex maps/mods generally use GZDoom Builder instead (which is Windows-only) :slightly_smiling_face: 

Also, people typically use ZScript instead of ACS for scripting in modern source ports.

**Comment by Eonfge** [comment]
@Calinou Fair enough. I made an issue over at SLADE to highlight some of the issues that should be addressed upstream: https://github.com/sirjuddington/SLADE/issues/1093

As for now, I'll publish the Soundfont and the ACC compiler. Perhaps in the future, we can add the further improve the Flatpak integration
